# OCS-KVM Platform modules

OCS_KVM_OCSV_PLATFORM_MODULE_VERSION = 1.0
export OCS_KVM_OCSV_PLATFORM_MODULE_VERSION

OCS_KVM_OCSV_PLATFORM_MODULE = sonic-platform-ocs-kvm-ocs-v_$(OCS_KVM_OCSV_PLATFORM_MODULE_VERSION)_amd64.deb
$(OCS_KVM_OCSV_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-ocs-kvm
$(OCS_KVM_OCSV_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(OCS_KVM_OCSV_PLATFORM_MODULE)_PLATFORM = x86_64-ocs-kvm_x86_64-r0

SONIC_DPKG_DEBS += $(OCS_KVM_OCSV_PLATFORM_MODULE)
