LIBSAI_VERSION = 1.0.0
OCS_KVM_LIBSAI_DEB = libsai-ocs-kvm-$(LIBSAI_VERSION)-amd64.deb
$(OCS_KVM_LIBSAI_DEB)_URL = "$(OCS_LIBS_RELEASE_URL)/$(OCS_KVM_LIBSAI_DEB)"

SONIC_ONLINE_DEBS += $(OCS_KVM_LIBSAI_DEB)
